# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Backend CI

on:
  #This ensures the workflow only triggers when files inside backend/ change
  push:
    branches: ["dev", "main"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["dev", "main"]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    #This ensures the npm command runs inside backend/ and not root
    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - run: npm ci

      # Set up test environment variables
      - name: Create .env.test file
        run: |
          echo "DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}" > .env.test
          echo "GOOGLE_APPLICATION_CREDENTIALS=./firebaseServiceAccountKey.json" >> .env.test
      # Create Firebase service account file from secret
      - name: Create Firebase service account
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebaseServiceAccountKey.json

      # Run Prisma migrations on test database
      - name: Run migrations
        run: npm run test:migrate
      - run: npm run test
      - run: npm run lint
